source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

xcodeproj 'DYCopy.xcodeproj'

target 'DYCopy' do
pod 'SDCycleScrollView','~> 1.64'
pod 'BMPlayer'
pod 'Alamofire', '~> 4.0'
pod 'SwiftyJSON'
pod 'ObjectMapper', '~> 2.2'
pod 'Kingfisher', '~> 3.0'
pod 'ESPullToRefresh'
pod 'LFLiveKit'
end
